# Base default values for elk stack
elasticsearch:
  replicaCount: 1
  image:
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: 8.11.3
    pullPolicy: IfNotPresent
  discoveryType: single-node
  javaOpts: "-Xms512m -Xmx512m"
  service:
    type: ClusterIP
  persistence:
    enabled: true
    size: 10Gi
  resources:
    requests:
      cpu: 250m
      memory: 768Mi
    limits:
      cpu: 1000m
      memory: 1.5Gi

logstash:
  replicaCount: 1
  image:
    repository: docker.elastic.co/logstash/logstash
    tag: 8.11.3
    pullPolicy: IfNotPresent
  javaOpts: "-Xms256m -Xmx256m"
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 100m
      memory: 384Mi
    limits:
      cpu: 500m
      memory: 768Mi

kibana:
  replicaCount: 1
  image:
    repository: docker.elastic.co/kibana/kibana
    tag: 8.11.3
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
