# Dev EU-West-1 values for elk stack
elasticsearch:
  replicaCount: 1
  javaOpts: "-Xms384m -Xmx384m"
  persistence:
    enabled: true
    size: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

logstash:
  replicaCount: 1
  javaOpts: "-Xms192m -Xmx192m"
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi

kibana:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi
