packages:
  - 'hubs/*'
  - 'proto'
  - 'design-system'
  - 'observability'

allowBuilds:
  '@apollo/protobufjs': true
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': false
  esbuild: true
  lightningcss: true
  prisma: true
  protobufjs: false
