apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web.fullname" . }}-config
  labels:
    {{- include "web.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.env.PORT | default "3000" | quote }}
  NODE_ENV: {{ .Values.env.NODE_ENV | default "production" | quote }}
  DOMAIN_HUB_URL: {{ .Values.env.DOMAIN_HUB_URL | default "http://domain-hub:8000/graphql" | quote }}
