apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notification-hub.fullname" . }}-config
  labels:
    {{- include "notification-hub.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.env.PORT | default "8001" | quote }}
