apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "elk.fullname" . }}-kibana
  labels:
    {{- include "elk.labels" . | nindent 4 }}
    app: kibana
spec:
  replicas: {{ .Values.kibana.replicaCount }}
  selector:
    matchLabels:
      app: kibana
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: kibana
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: kibana
          image: "{{ .Values.kibana.image.repository }}:{{ .Values.kibana.image.tag }}"
          imagePullPolicy: {{ .Values.kibana.image.pullPolicy }}
          ports:
            - containerPort: 5601
              name: http
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch:9200"
          resources:
            {{- toYaml .Values.kibana.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    {{- include "elk.labels" . | nindent 4 }}
    app: kibana
spec:
  type: {{ .Values.kibana.service.type }}
  ports:
    - port: 5601
      targetPort: 5601
      name: http
  selector:
    app: kibana
    app.kubernetes.io/instance: {{ .Release.Name }}
