apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "elk.fullname" . }}-logstash
  labels:
    {{- include "elk.labels" . | nindent 4 }}
    app: logstash
spec:
  replicas: {{ .Values.logstash.replicaCount }}
  selector:
    matchLabels:
      app: logstash
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: logstash
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: logstash
          image: "{{ .Values.logstash.image.repository }}:{{ .Values.logstash.image.tag }}"
          imagePullPolicy: {{ .Values.logstash.image.pullPolicy }}
          ports:
            - containerPort: 5044
              name: beats
            - containerPort: 5000
              name: tcp
            - containerPort: 8080
              name: http
          env:
            - name: LS_JAVA_OPTS
              value: {{ .Values.logstash.javaOpts | quote }}
          volumeMounts:
            - name: pipeline
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
          resources:
            {{- toYaml .Values.logstash.resources | nindent 12 }}
      volumes:
        - name: pipeline
          configMap:
            name: {{ include "elk.fullname" . }}-logstash-pipeline
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    {{- include "elk.labels" . | nindent 4 }}
    app: logstash
spec:
  type: {{ .Values.logstash.service.type }}
  ports:
    - port: 5044
      targetPort: 5044
      name: beats
    - port: 5000
      targetPort: 5000
      name: tcp
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: logstash
    app.kubernetes.io/instance: {{ .Release.Name }}
