/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as ConfigIndexRouteImport } from './routes/config/index'
import { Route as EnrollersIndexRouteImport } from './routes/enrollers/index'
import { Route as EnrollersDashboardRouteImport } from './routes/enrollers/dashboard'
import { Route as LecturesIndexRouteImport } from './routes/lectures/index'
import { Route as LecturesVideoIdRouteImport } from './routes/lectures/$videoId'
import { Route as TeachersIndexRouteImport } from './routes/teachers/index'
import { Route as TeachersLecturesRouteImport } from './routes/teachers/lectures'
import { Route as TeachersRequestsRouteImport } from './routes/teachers/requests'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as UsersUserIdRouteRouteImport } from './routes/users/$userId/route'
import { Route as PublicUserIdIndexRouteImport } from './routes/public/$userId/index'
import { Route as UsersUserIdIndexRouteImport } from './routes/users/$userId/index'
import { Route as UsersUserIdAvailabilityIndexRouteImport } from './routes/users/$userId/availability/index'
import { Route as UsersUserIdBookingsIndexRouteImport } from './routes/users/$userId/bookings/index'
import { Route as UsersUserIdEventTypesIndexRouteImport } from './routes/users/$userId/event-types/index'
import { Route as UsersUserIdEventTypesNewRouteImport } from './routes/users/$userId/event-types/new'
import { Route as UsersUserIdSlotsIndexRouteImport } from './routes/users/$userId/slots/index'
import { Route as PublicUserIdEventTypesEventTypeSlugIndexRouteImport } from './routes/public/$userId/event-types/$eventTypeSlug/index'
import { Route as UsersUserIdEventTypesEventTypeSlugIndexRouteImport } from './routes/users/$userId/event-types/$eventTypeSlug/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigIndexRoute = ConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollersIndexRoute = EnrollersIndexRouteImport.update({
  id: '/enrollers/',
  path: '/enrollers/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollersDashboardRoute = EnrollersDashboardRouteImport.update({
  id: '/enrollers/dashboard',
  path: '/enrollers/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturesIndexRoute = LecturesIndexRouteImport.update({
  id: '/lectures/',
  path: '/lectures/',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturesVideoIdRoute = LecturesVideoIdRouteImport.update({
  id: '/lectures/$videoId',
  path: '/lectures/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersIndexRoute = TeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersLecturesRoute = TeachersLecturesRouteImport.update({
  id: '/teachers/lectures',
  path: '/teachers/lectures',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRequestsRoute = TeachersRequestsRouteImport.update({
  id: '/teachers/requests',
  path: '/teachers/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRouteRoute = UsersUserIdRouteRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicUserIdIndexRoute = PublicUserIdIndexRouteImport.update({
  id: '/public/$userId/',
  path: '/public/$userId/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdIndexRoute = UsersUserIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersUserIdRouteRoute,
} as any)
const UsersUserIdAvailabilityIndexRoute =
  UsersUserIdAvailabilityIndexRouteImport.update({
    id: '/availability/',
    path: '/availability/',
    getParentRoute: () => UsersUserIdRouteRoute,
  } as any)
const UsersUserIdBookingsIndexRoute =
  UsersUserIdBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => UsersUserIdRouteRoute,
  } as any)
const UsersUserIdEventTypesIndexRoute =
  UsersUserIdEventTypesIndexRouteImport.update({
    id: '/event-types/',
    path: '/event-types/',
    getParentRoute: () => UsersUserIdRouteRoute,
  } as any)
const UsersUserIdEventTypesNewRoute =
  UsersUserIdEventTypesNewRouteImport.update({
    id: '/event-types/new',
    path: '/event-types/new',
    getParentRoute: () => UsersUserIdRouteRoute,
  } as any)
const UsersUserIdSlotsIndexRoute = UsersUserIdSlotsIndexRouteImport.update({
  id: '/slots/',
  path: '/slots/',
  getParentRoute: () => UsersUserIdRouteRoute,
} as any)
const PublicUserIdEventTypesEventTypeSlugIndexRoute =
  PublicUserIdEventTypesEventTypeSlugIndexRouteImport.update({
    id: '/public/$userId/event-types/$eventTypeSlug/',
    path: '/public/$userId/event-types/$eventTypeSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UsersUserIdEventTypesEventTypeSlugIndexRoute =
  UsersUserIdEventTypesEventTypeSlugIndexRouteImport.update({
    id: '/event-types/$eventTypeSlug/',
    path: '/event-types/$eventTypeSlug/',
    getParentRoute: () => UsersUserIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/users/$userId': typeof UsersUserIdRouteRouteWithChildren
  '/enrollers/dashboard': typeof EnrollersDashboardRoute
  '/lectures/$videoId': typeof LecturesVideoIdRoute
  '/teachers/lectures': typeof TeachersLecturesRoute
  '/teachers/requests': typeof TeachersRequestsRoute
  '/config/': typeof ConfigIndexRoute
  '/enrollers/': typeof EnrollersIndexRoute
  '/lectures/': typeof LecturesIndexRoute
  '/teachers/': typeof TeachersIndexRoute
  '/users/': typeof UsersIndexRoute
  '/public/$userId/': typeof PublicUserIdIndexRoute
  '/users/$userId/': typeof UsersUserIdIndexRoute
  '/users/$userId/event-types/new': typeof UsersUserIdEventTypesNewRoute
  '/users/$userId/availability/': typeof UsersUserIdAvailabilityIndexRoute
  '/users/$userId/bookings/': typeof UsersUserIdBookingsIndexRoute
  '/users/$userId/event-types/': typeof UsersUserIdEventTypesIndexRoute
  '/users/$userId/slots/': typeof UsersUserIdSlotsIndexRoute
  '/public/$userId/event-types/$eventTypeSlug/': typeof PublicUserIdEventTypesEventTypeSlugIndexRoute
  '/users/$userId/event-types/$eventTypeSlug/': typeof UsersUserIdEventTypesEventTypeSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/enrollers/dashboard': typeof EnrollersDashboardRoute
  '/lectures/$videoId': typeof LecturesVideoIdRoute
  '/teachers/lectures': typeof TeachersLecturesRoute
  '/teachers/requests': typeof TeachersRequestsRoute
  '/config': typeof ConfigIndexRoute
  '/enrollers': typeof EnrollersIndexRoute
  '/lectures': typeof LecturesIndexRoute
  '/teachers': typeof TeachersIndexRoute
  '/users': typeof UsersIndexRoute
  '/public/$userId': typeof PublicUserIdIndexRoute
  '/users/$userId': typeof UsersUserIdIndexRoute
  '/users/$userId/event-types/new': typeof UsersUserIdEventTypesNewRoute
  '/users/$userId/availability': typeof UsersUserIdAvailabilityIndexRoute
  '/users/$userId/bookings': typeof UsersUserIdBookingsIndexRoute
  '/users/$userId/event-types': typeof UsersUserIdEventTypesIndexRoute
  '/users/$userId/slots': typeof UsersUserIdSlotsIndexRoute
  '/public/$userId/event-types/$eventTypeSlug': typeof PublicUserIdEventTypesEventTypeSlugIndexRoute
  '/users/$userId/event-types/$eventTypeSlug': typeof UsersUserIdEventTypesEventTypeSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/users/$userId': typeof UsersUserIdRouteRouteWithChildren
  '/enrollers/dashboard': typeof EnrollersDashboardRoute
  '/lectures/$videoId': typeof LecturesVideoIdRoute
  '/teachers/lectures': typeof TeachersLecturesRoute
  '/teachers/requests': typeof TeachersRequestsRoute
  '/config/': typeof ConfigIndexRoute
  '/enrollers/': typeof EnrollersIndexRoute
  '/lectures/': typeof LecturesIndexRoute
  '/teachers/': typeof TeachersIndexRoute
  '/users/': typeof UsersIndexRoute
  '/public/$userId/': typeof PublicUserIdIndexRoute
  '/users/$userId/': typeof UsersUserIdIndexRoute
  '/users/$userId/event-types/new': typeof UsersUserIdEventTypesNewRoute
  '/users/$userId/availability/': typeof UsersUserIdAvailabilityIndexRoute
  '/users/$userId/bookings/': typeof UsersUserIdBookingsIndexRoute
  '/users/$userId/event-types/': typeof UsersUserIdEventTypesIndexRoute
  '/users/$userId/slots/': typeof UsersUserIdSlotsIndexRoute
  '/public/$userId/event-types/$eventTypeSlug/': typeof PublicUserIdEventTypesEventTypeSlugIndexRoute
  '/users/$userId/event-types/$eventTypeSlug/': typeof UsersUserIdEventTypesEventTypeSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/users/$userId'
    | '/enrollers/dashboard'
    | '/lectures/$videoId'
    | '/teachers/lectures'
    | '/teachers/requests'
    | '/config/'
    | '/enrollers/'
    | '/lectures/'
    | '/teachers/'
    | '/users/'
    | '/public/$userId/'
    | '/users/$userId/'
    | '/users/$userId/event-types/new'
    | '/users/$userId/availability/'
    | '/users/$userId/bookings/'
    | '/users/$userId/event-types/'
    | '/users/$userId/slots/'
    | '/public/$userId/event-types/$eventTypeSlug/'
    | '/users/$userId/event-types/$eventTypeSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/enrollers/dashboard'
    | '/lectures/$videoId'
    | '/teachers/lectures'
    | '/teachers/requests'
    | '/config'
    | '/enrollers'
    | '/lectures'
    | '/teachers'
    | '/users'
    | '/public/$userId'
    | '/users/$userId'
    | '/users/$userId/event-types/new'
    | '/users/$userId/availability'
    | '/users/$userId/bookings'
    | '/users/$userId/event-types'
    | '/users/$userId/slots'
    | '/public/$userId/event-types/$eventTypeSlug'
    | '/users/$userId/event-types/$eventTypeSlug'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/logout'
    | '/users/$userId'
    | '/enrollers/dashboard'
    | '/lectures/$videoId'
    | '/teachers/lectures'
    | '/teachers/requests'
    | '/config/'
    | '/enrollers/'
    | '/lectures/'
    | '/teachers/'
    | '/users/'
    | '/public/$userId/'
    | '/users/$userId/'
    | '/users/$userId/event-types/new'
    | '/users/$userId/availability/'
    | '/users/$userId/bookings/'
    | '/users/$userId/event-types/'
    | '/users/$userId/slots/'
    | '/public/$userId/event-types/$eventTypeSlug/'
    | '/users/$userId/event-types/$eventTypeSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  UsersUserIdRouteRoute: typeof UsersUserIdRouteRouteWithChildren
  EnrollersDashboardRoute: typeof EnrollersDashboardRoute
  LecturesVideoIdRoute: typeof LecturesVideoIdRoute
  TeachersLecturesRoute: typeof TeachersLecturesRoute
  TeachersRequestsRoute: typeof TeachersRequestsRoute
  ConfigIndexRoute: typeof ConfigIndexRoute
  EnrollersIndexRoute: typeof EnrollersIndexRoute
  LecturesIndexRoute: typeof LecturesIndexRoute
  TeachersIndexRoute: typeof TeachersIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  PublicUserIdIndexRoute: typeof PublicUserIdIndexRoute
  PublicUserIdEventTypesEventTypeSlugIndexRoute: typeof PublicUserIdEventTypesEventTypeSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/': {
      id: '/config/'
      path: '/config'
      fullPath: '/config/'
      preLoaderRoute: typeof ConfigIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enrollers/': {
      id: '/enrollers/'
      path: '/enrollers'
      fullPath: '/enrollers/'
      preLoaderRoute: typeof EnrollersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enrollers/dashboard': {
      id: '/enrollers/dashboard'
      path: '/enrollers/dashboard'
      fullPath: '/enrollers/dashboard'
      preLoaderRoute: typeof EnrollersDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lectures/': {
      id: '/lectures/'
      path: '/lectures'
      fullPath: '/lectures/'
      preLoaderRoute: typeof LecturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lectures/$videoId': {
      id: '/lectures/$videoId'
      path: '/lectures/$videoId'
      fullPath: '/lectures/$videoId'
      preLoaderRoute: typeof LecturesVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/': {
      id: '/teachers/'
      path: '/teachers'
      fullPath: '/teachers/'
      preLoaderRoute: typeof TeachersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/lectures': {
      id: '/teachers/lectures'
      path: '/teachers/lectures'
      fullPath: '/teachers/lectures'
      preLoaderRoute: typeof TeachersLecturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/requests': {
      id: '/teachers/requests'
      path: '/teachers/requests'
      fullPath: '/teachers/requests'
      preLoaderRoute: typeof TeachersRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/$userId/': {
      id: '/public/$userId/'
      path: '/public/$userId'
      fullPath: '/public/$userId/'
      preLoaderRoute: typeof PublicUserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId/': {
      id: '/users/$userId/'
      path: '/'
      fullPath: '/users/$userId/'
      preLoaderRoute: typeof UsersUserIdIndexRouteImport
      parentRoute: typeof UsersUserIdRouteRoute
    }
    '/users/$userId/availability/': {
      id: '/users/$userId/availability/'
      path: '/availability'
      fullPath: '/users/$userId/availability/'
      preLoaderRoute: typeof UsersUserIdAvailabilityIndexRouteImport
      parentRoute: typeof UsersUserIdRouteRoute
    }
    '/users/$userId/bookings/': {
      id: '/users/$userId/bookings/'
      path: '/bookings'
      fullPath: '/users/$userId/bookings/'
      preLoaderRoute: typeof UsersUserIdBookingsIndexRouteImport
      parentRoute: typeof UsersUserIdRouteRoute
    }
    '/users/$userId/event-types/': {
      id: '/users/$userId/event-types/'
      path: '/event-types'
      fullPath: '/users/$userId/event-types/'
      preLoaderRoute: typeof UsersUserIdEventTypesIndexRouteImport
      parentRoute: typeof UsersUserIdRouteRoute
    }
    '/users/$userId/event-types/new': {
      id: '/users/$userId/event-types/new'
      path: '/event-types/new'
      fullPath: '/users/$userId/event-types/new'
      preLoaderRoute: typeof UsersUserIdEventTypesNewRouteImport
      parentRoute: typeof UsersUserIdRouteRoute
    }
    '/users/$userId/slots/': {
      id: '/users/$userId/slots/'
      path: '/slots'
      fullPath: '/users/$userId/slots/'
      preLoaderRoute: typeof UsersUserIdSlotsIndexRouteImport
      parentRoute: typeof UsersUserIdRouteRoute
    }
    '/public/$userId/event-types/$eventTypeSlug/': {
      id: '/public/$userId/event-types/$eventTypeSlug/'
      path: '/public/$userId/event-types/$eventTypeSlug'
      fullPath: '/public/$userId/event-types/$eventTypeSlug/'
      preLoaderRoute: typeof PublicUserIdEventTypesEventTypeSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId/event-types/$eventTypeSlug/': {
      id: '/users/$userId/event-types/$eventTypeSlug/'
      path: '/event-types/$eventTypeSlug'
      fullPath: '/users/$userId/event-types/$eventTypeSlug/'
      preLoaderRoute: typeof UsersUserIdEventTypesEventTypeSlugIndexRouteImport
      parentRoute: typeof UsersUserIdRouteRoute
    }
  }
}

interface UsersUserIdRouteRouteChildren {
  UsersUserIdIndexRoute: typeof UsersUserIdIndexRoute
  UsersUserIdEventTypesNewRoute: typeof UsersUserIdEventTypesNewRoute
  UsersUserIdAvailabilityIndexRoute: typeof UsersUserIdAvailabilityIndexRoute
  UsersUserIdBookingsIndexRoute: typeof UsersUserIdBookingsIndexRoute
  UsersUserIdEventTypesIndexRoute: typeof UsersUserIdEventTypesIndexRoute
  UsersUserIdSlotsIndexRoute: typeof UsersUserIdSlotsIndexRoute
  UsersUserIdEventTypesEventTypeSlugIndexRoute: typeof UsersUserIdEventTypesEventTypeSlugIndexRoute
}

const UsersUserIdRouteRouteChildren: UsersUserIdRouteRouteChildren = {
  UsersUserIdIndexRoute: UsersUserIdIndexRoute,
  UsersUserIdEventTypesNewRoute: UsersUserIdEventTypesNewRoute,
  UsersUserIdAvailabilityIndexRoute: UsersUserIdAvailabilityIndexRoute,
  UsersUserIdBookingsIndexRoute: UsersUserIdBookingsIndexRoute,
  UsersUserIdEventTypesIndexRoute: UsersUserIdEventTypesIndexRoute,
  UsersUserIdSlotsIndexRoute: UsersUserIdSlotsIndexRoute,
  UsersUserIdEventTypesEventTypeSlugIndexRoute:
    UsersUserIdEventTypesEventTypeSlugIndexRoute,
}

const UsersUserIdRouteRouteWithChildren =
  UsersUserIdRouteRoute._addFileChildren(UsersUserIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  UsersUserIdRouteRoute: UsersUserIdRouteRouteWithChildren,
  EnrollersDashboardRoute: EnrollersDashboardRoute,
  LecturesVideoIdRoute: LecturesVideoIdRoute,
  TeachersLecturesRoute: TeachersLecturesRoute,
  TeachersRequestsRoute: TeachersRequestsRoute,
  ConfigIndexRoute: ConfigIndexRoute,
  EnrollersIndexRoute: EnrollersIndexRoute,
  LecturesIndexRoute: LecturesIndexRoute,
  TeachersIndexRoute: TeachersIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  PublicUserIdIndexRoute: PublicUserIdIndexRoute,
  PublicUserIdEventTypesEventTypeSlugIndexRoute:
    PublicUserIdEventTypesEventTypeSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
