apiVersion: v1
kind: Service
metadata:
  name: {{ include "leader-hub.fullname" . }}
  labels:
    {{- include "leader-hub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8007
      name: http
      protocol: TCP
  selector:
    {{- include "leader-hub.selectorLabels" . | nindent 4 }}
