apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "search-hub.fullname" . }}-config
  labels:
    {{- include "search-hub.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.env.PORT | default "8002" | quote }}
