apiVersion: v1
kind: Service
metadata:
  name: {{ include "temporal.fullname" . }}
  labels:
    {{- include "temporal.labels" . | nindent 4 }}
    app: temporal-server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: 7233
      name: grpc
  selector:
    app: temporal-server
    app.kubernetes.io/instance: {{ .Release.Name }}
