apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cohort-root-app
  namespace: argocd
  labels:
    app.kubernetes.io/name: cohort-root-app
    app.kubernetes.io/part-of: cohort-platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cohort-platform
  source:
    repoURL: 'https://github.com/venkatkadiri/Cohort.git'
    targetRevision: HEAD
    path: argocd/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
