apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "leader-hub.fullname" . }}-config
  labels:
    {{- include "leader-hub.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.service.port | quote }}
  NODE_ENV: {{ .Values.env.NODE_ENV | default "production" | quote }}
  TEMPORAL_ADDRESS: {{ .Values.env.TEMPORAL_ADDRESS | default "temporal:7233" | quote }}
