# Default base values for postgres
replicaCount: 1

image:
  repository: postgres
  tag: 15-alpine
  pullPolicy: IfNotPresent

auth:
  username: temporal
  password: temporal
  database: temporal

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClass: ""

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
