# Production overrides for postgres
replicaCount: 1

persistence:
  enabled: true
  size: 100Gi
  storageClass: "gp3"

resources:
  requests:
    cpu: 1000m
    memory: 2Gi
  limits:
    cpu: 2000m
    memory: 4Gi
