apiVersion: v1
kind: Service
metadata:
  name: {{ include "transaction-hub.fullname" . }}
  labels:
    {{- include "transaction-hub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8008
      name: http
      protocol: TCP
  selector:
    {{- include "transaction-hub.selectorLabels" . | nindent 4 }}
