apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: '[cohort-logs-]YYYY.MM.DD'
    jsonData:
      esVersion: '8.0.0'
      timeField: '@timestamp'
      interval: Daily
    editable: true
