apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth-hub.fullname" . }}-config
  labels:
    {{- include "auth-hub.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.env.PORT | default "8003" | quote }}
  JWT_SECRET: {{ .Values.env.JWT_SECRET | default "cohort-jwt-secret-dev" | quote }}
