apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-hub.fullname" . }}
  labels:
    {{- include "auth-hub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8003
      name: http
      protocol: TCP
    - port: {{ .Values.service.grpcPort }}
      targetPort: 50054
      name: grpc
      protocol: TCP
  selector:
    {{- include "auth-hub.selectorLabels" . | nindent 4 }}
