apiVersion: v1
kind: Service
metadata:
  name: {{ include "video-hub.fullname" . }}
  labels:
    {{- include "video-hub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8005
      name: http
      protocol: TCP
    - port: {{ .Values.service.grpcPort }}
      targetPort: 50055
      name: grpc
      protocol: TCP
  selector:
    {{- include "video-hub.selectorLabels" . | nindent 4 }}
