apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres.yaml
  - temporal.yaml
  - hub-domain.yaml
  - spoke-booking.yaml
  - spoke-notification.yaml
  - spoke-search.yaml
  - spoke-auth.yaml
  - spoke-video.yaml
  - spoke-config.yaml
  - web-frontend.yaml
  - ingress.yaml
  - observability/
  - keda/

commonLabels:
  app.kubernetes.io/part-of: cohort-platform
  app.kubernetes.io/managed-by: kustomize
