apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "video-hub.fullname" . }}-config
  labels:
    {{- include "video-hub.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.env.PORT | default "8005" | quote }}
