apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "video-hub.fullname" . }}
  labels:
    {{- include "video-hub.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "video-hub.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "video-hub.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: video-hub
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8005
              name: http
            - containerPort: 50055
              name: grpc
          envFrom:
            - configMapRef:
                name: {{ include "video-hub.fullname" . }}-config
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessPath }}
              port: 8005
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.livenessPath }}
              port: 8005
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
