apiVersion: v1
kind: Secret
metadata:
  name: keda-postgres-secrets
type: Opaque
stringData:
  connectionString: "postgresql://cohort_user:cohort_secure_password_2026@postgres:5432/cohort_db?sslmode=disable"
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-postgres
spec:
  secretTargetRef:
    - parameter: connectionString
      name: keda-postgres-secrets
      key: connectionString
