# Environment: dev-eu-west1 (Ireland)
replicaCount: 1

ingress:
  enabled: true
  host: dev-eu-west1.cohort.mesh

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

autoscaling:
  enabled: false

podDisruptionBudget:
  enabled: false
