# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.proto import cohort_pb2 as cohort__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cohort_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListUsers = channel.unary_unary(
                '/cohort.UserService/ListUsers',
                request_serializer=cohort__pb2.Empty.SerializeToString,
                response_deserializer=cohort__pb2.ListUsersResponse.FromString,
                _registered_method=True)
        self.GetUserById = channel.unary_unary(
                '/cohort.UserService/GetUserById',
                request_serializer=cohort__pb2.GetUserRequest.SerializeToString,
                response_deserializer=cohort__pb2.UserModel.FromString,
                _registered_method=True)
        self.GetUserBySlug = channel.unary_unary(
                '/cohort.UserService/GetUserBySlug',
                request_serializer=cohort__pb2.GetUserRequest.SerializeToString,
                response_deserializer=cohort__pb2.UserModel.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/cohort.UserService/CreateUser',
                request_serializer=cohort__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=cohort__pb2.UserModel.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/cohort.UserService/UpdateUser',
                request_serializer=cohort__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=cohort__pb2.UserModel.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/cohort.UserService/DeleteUser',
                request_serializer=cohort__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=cohort__pb2.StatusResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserBySlug(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=cohort__pb2.Empty.FromString,
                    response_serializer=cohort__pb2.ListUsersResponse.SerializeToString,
            ),
            'GetUserById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserById,
                    request_deserializer=cohort__pb2.GetUserRequest.FromString,
                    response_serializer=cohort__pb2.UserModel.SerializeToString,
            ),
            'GetUserBySlug': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserBySlug,
                    request_deserializer=cohort__pb2.GetUserRequest.FromString,
                    response_serializer=cohort__pb2.UserModel.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=cohort__pb2.CreateUserRequest.FromString,
                    response_serializer=cohort__pb2.UserModel.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=cohort__pb2.UpdateUserRequest.FromString,
                    response_serializer=cohort__pb2.UserModel.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=cohort__pb2.DeleteUserRequest.FromString,
                    response_serializer=cohort__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cohort.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cohort.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.UserService/ListUsers',
            cohort__pb2.Empty.SerializeToString,
            cohort__pb2.ListUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.UserService/GetUserById',
            cohort__pb2.GetUserRequest.SerializeToString,
            cohort__pb2.UserModel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserBySlug(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.UserService/GetUserBySlug',
            cohort__pb2.GetUserRequest.SerializeToString,
            cohort__pb2.UserModel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.UserService/CreateUser',
            cohort__pb2.CreateUserRequest.SerializeToString,
            cohort__pb2.UserModel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.UserService/UpdateUser',
            cohort__pb2.UpdateUserRequest.SerializeToString,
            cohort__pb2.UserModel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.UserService/DeleteUser',
            cohort__pb2.DeleteUserRequest.SerializeToString,
            cohort__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EventTypeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListEventTypes = channel.unary_unary(
                '/cohort.EventTypeService/ListEventTypes',
                request_serializer=cohort__pb2.ListEventTypesRequest.SerializeToString,
                response_deserializer=cohort__pb2.ListEventTypesResponse.FromString,
                _registered_method=True)
        self.GetEventTypeById = channel.unary_unary(
                '/cohort.EventTypeService/GetEventTypeById',
                request_serializer=cohort__pb2.GetEventTypeRequest.SerializeToString,
                response_deserializer=cohort__pb2.EventTypeModel.FromString,
                _registered_method=True)
        self.GetEventTypeBySlug = channel.unary_unary(
                '/cohort.EventTypeService/GetEventTypeBySlug',
                request_serializer=cohort__pb2.GetEventTypeRequest.SerializeToString,
                response_deserializer=cohort__pb2.EventTypeModel.FromString,
                _registered_method=True)
        self.GetPublicEventType = channel.unary_unary(
                '/cohort.EventTypeService/GetPublicEventType',
                request_serializer=cohort__pb2.GetEventTypeRequest.SerializeToString,
                response_deserializer=cohort__pb2.PublicEventTypeResponse.FromString,
                _registered_method=True)
        self.CreateEventType = channel.unary_unary(
                '/cohort.EventTypeService/CreateEventType',
                request_serializer=cohort__pb2.CreateEventTypeRequest.SerializeToString,
                response_deserializer=cohort__pb2.EventTypeModel.FromString,
                _registered_method=True)
        self.UpdateEventType = channel.unary_unary(
                '/cohort.EventTypeService/UpdateEventType',
                request_serializer=cohort__pb2.UpdateEventTypeRequest.SerializeToString,
                response_deserializer=cohort__pb2.EventTypeModel.FromString,
                _registered_method=True)
        self.DeleteEventType = channel.unary_unary(
                '/cohort.EventTypeService/DeleteEventType',
                request_serializer=cohort__pb2.DeleteEventTypeRequest.SerializeToString,
                response_deserializer=cohort__pb2.StatusResponse.FromString,
                _registered_method=True)


class EventTypeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListEventTypes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEventTypeById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEventTypeBySlug(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPublicEventType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEventType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEventType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEventType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventTypeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListEventTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEventTypes,
                    request_deserializer=cohort__pb2.ListEventTypesRequest.FromString,
                    response_serializer=cohort__pb2.ListEventTypesResponse.SerializeToString,
            ),
            'GetEventTypeById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEventTypeById,
                    request_deserializer=cohort__pb2.GetEventTypeRequest.FromString,
                    response_serializer=cohort__pb2.EventTypeModel.SerializeToString,
            ),
            'GetEventTypeBySlug': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEventTypeBySlug,
                    request_deserializer=cohort__pb2.GetEventTypeRequest.FromString,
                    response_serializer=cohort__pb2.EventTypeModel.SerializeToString,
            ),
            'GetPublicEventType': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPublicEventType,
                    request_deserializer=cohort__pb2.GetEventTypeRequest.FromString,
                    response_serializer=cohort__pb2.PublicEventTypeResponse.SerializeToString,
            ),
            'CreateEventType': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEventType,
                    request_deserializer=cohort__pb2.CreateEventTypeRequest.FromString,
                    response_serializer=cohort__pb2.EventTypeModel.SerializeToString,
            ),
            'UpdateEventType': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEventType,
                    request_deserializer=cohort__pb2.UpdateEventTypeRequest.FromString,
                    response_serializer=cohort__pb2.EventTypeModel.SerializeToString,
            ),
            'DeleteEventType': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEventType,
                    request_deserializer=cohort__pb2.DeleteEventTypeRequest.FromString,
                    response_serializer=cohort__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cohort.EventTypeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cohort.EventTypeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventTypeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListEventTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.EventTypeService/ListEventTypes',
            cohort__pb2.ListEventTypesRequest.SerializeToString,
            cohort__pb2.ListEventTypesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEventTypeById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.EventTypeService/GetEventTypeById',
            cohort__pb2.GetEventTypeRequest.SerializeToString,
            cohort__pb2.EventTypeModel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEventTypeBySlug(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.EventTypeService/GetEventTypeBySlug',
            cohort__pb2.GetEventTypeRequest.SerializeToString,
            cohort__pb2.EventTypeModel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPublicEventType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.EventTypeService/GetPublicEventType',
            cohort__pb2.GetEventTypeRequest.SerializeToString,
            cohort__pb2.PublicEventTypeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateEventType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.EventTypeService/CreateEventType',
            cohort__pb2.CreateEventTypeRequest.SerializeToString,
            cohort__pb2.EventTypeModel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEventType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.EventTypeService/UpdateEventType',
            cohort__pb2.UpdateEventTypeRequest.SerializeToString,
            cohort__pb2.EventTypeModel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEventType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.EventTypeService/DeleteEventType',
            cohort__pb2.DeleteEventTypeRequest.SerializeToString,
            cohort__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AvailabilityServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListRules = channel.unary_unary(
                '/cohort.AvailabilityService/ListRules',
                request_serializer=cohort__pb2.ListAvailabilityRequest.SerializeToString,
                response_deserializer=cohort__pb2.ListRulesResponse.FromString,
                _registered_method=True)
        self.CreateRule = channel.unary_unary(
                '/cohort.AvailabilityService/CreateRule',
                request_serializer=cohort__pb2.CreateRuleRequest.SerializeToString,
                response_deserializer=cohort__pb2.AvailabilityRuleModel.FromString,
                _registered_method=True)
        self.UpdateRule = channel.unary_unary(
                '/cohort.AvailabilityService/UpdateRule',
                request_serializer=cohort__pb2.UpdateRuleRequest.SerializeToString,
                response_deserializer=cohort__pb2.AvailabilityRuleModel.FromString,
                _registered_method=True)
        self.DeleteRule = channel.unary_unary(
                '/cohort.AvailabilityService/DeleteRule',
                request_serializer=cohort__pb2.DeleteRuleRequest.SerializeToString,
                response_deserializer=cohort__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ListExceptions = channel.unary_unary(
                '/cohort.AvailabilityService/ListExceptions',
                request_serializer=cohort__pb2.ListExceptionsRequest.SerializeToString,
                response_deserializer=cohort__pb2.ListExceptionsResponse.FromString,
                _registered_method=True)
        self.CreateException = channel.unary_unary(
                '/cohort.AvailabilityService/CreateException',
                request_serializer=cohort__pb2.CreateExceptionRequest.SerializeToString,
                response_deserializer=cohort__pb2.AvailabilityExceptionModel.FromString,
                _registered_method=True)
        self.UpdateException = channel.unary_unary(
                '/cohort.AvailabilityService/UpdateException',
                request_serializer=cohort__pb2.UpdateExceptionRequest.SerializeToString,
                response_deserializer=cohort__pb2.AvailabilityExceptionModel.FromString,
                _registered_method=True)
        self.DeleteException = channel.unary_unary(
                '/cohort.AvailabilityService/DeleteException',
                request_serializer=cohort__pb2.DeleteExceptionRequest.SerializeToString,
                response_deserializer=cohort__pb2.StatusResponse.FromString,
                _registered_method=True)


class AvailabilityServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListRules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListExceptions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateException(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateException(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteException(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AvailabilityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListRules': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRules,
                    request_deserializer=cohort__pb2.ListAvailabilityRequest.FromString,
                    response_serializer=cohort__pb2.ListRulesResponse.SerializeToString,
            ),
            'CreateRule': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRule,
                    request_deserializer=cohort__pb2.CreateRuleRequest.FromString,
                    response_serializer=cohort__pb2.AvailabilityRuleModel.SerializeToString,
            ),
            'UpdateRule': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRule,
                    request_deserializer=cohort__pb2.UpdateRuleRequest.FromString,
                    response_serializer=cohort__pb2.AvailabilityRuleModel.SerializeToString,
            ),
            'DeleteRule': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRule,
                    request_deserializer=cohort__pb2.DeleteRuleRequest.FromString,
                    response_serializer=cohort__pb2.StatusResponse.SerializeToString,
            ),
            'ListExceptions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListExceptions,
                    request_deserializer=cohort__pb2.ListExceptionsRequest.FromString,
                    response_serializer=cohort__pb2.ListExceptionsResponse.SerializeToString,
            ),
            'CreateException': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateException,
                    request_deserializer=cohort__pb2.CreateExceptionRequest.FromString,
                    response_serializer=cohort__pb2.AvailabilityExceptionModel.SerializeToString,
            ),
            'UpdateException': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateException,
                    request_deserializer=cohort__pb2.UpdateExceptionRequest.FromString,
                    response_serializer=cohort__pb2.AvailabilityExceptionModel.SerializeToString,
            ),
            'DeleteException': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteException,
                    request_deserializer=cohort__pb2.DeleteExceptionRequest.FromString,
                    response_serializer=cohort__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cohort.AvailabilityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cohort.AvailabilityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AvailabilityService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.AvailabilityService/ListRules',
            cohort__pb2.ListAvailabilityRequest.SerializeToString,
            cohort__pb2.ListRulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.AvailabilityService/CreateRule',
            cohort__pb2.CreateRuleRequest.SerializeToString,
            cohort__pb2.AvailabilityRuleModel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.AvailabilityService/UpdateRule',
            cohort__pb2.UpdateRuleRequest.SerializeToString,
            cohort__pb2.AvailabilityRuleModel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.AvailabilityService/DeleteRule',
            cohort__pb2.DeleteRuleRequest.SerializeToString,
            cohort__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListExceptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.AvailabilityService/ListExceptions',
            cohort__pb2.ListExceptionsRequest.SerializeToString,
            cohort__pb2.ListExceptionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateException(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.AvailabilityService/CreateException',
            cohort__pb2.CreateExceptionRequest.SerializeToString,
            cohort__pb2.AvailabilityExceptionModel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateException(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.AvailabilityService/UpdateException',
            cohort__pb2.UpdateExceptionRequest.SerializeToString,
            cohort__pb2.AvailabilityExceptionModel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteException(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.AvailabilityService/DeleteException',
            cohort__pb2.DeleteExceptionRequest.SerializeToString,
            cohort__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SlotServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAvailableSlots = channel.unary_unary(
                '/cohort.SlotService/GetAvailableSlots',
                request_serializer=cohort__pb2.GetAvailableSlotsRequest.SerializeToString,
                response_deserializer=cohort__pb2.ListSlotsResponse.FromString,
                _registered_method=True)
        self.ListSlotsForHost = channel.unary_unary(
                '/cohort.SlotService/ListSlotsForHost',
                request_serializer=cohort__pb2.ListSlotsForHostRequest.SerializeToString,
                response_deserializer=cohort__pb2.ListSlotsResponse.FromString,
                _registered_method=True)
        self.CreateSlot = channel.unary_unary(
                '/cohort.SlotService/CreateSlot',
                request_serializer=cohort__pb2.CreateSlotRequest.SerializeToString,
                response_deserializer=cohort__pb2.SlotModel.FromString,
                _registered_method=True)
        self.UpdateSlot = channel.unary_unary(
                '/cohort.SlotService/UpdateSlot',
                request_serializer=cohort__pb2.UpdateSlotRequest.SerializeToString,
                response_deserializer=cohort__pb2.SlotModel.FromString,
                _registered_method=True)
        self.DeleteSlot = channel.unary_unary(
                '/cohort.SlotService/DeleteSlot',
                request_serializer=cohort__pb2.DeleteSlotRequest.SerializeToString,
                response_deserializer=cohort__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.RegenerateSlots = channel.unary_unary(
                '/cohort.SlotService/RegenerateSlots',
                request_serializer=cohort__pb2.RegenerateSlotsRequest.SerializeToString,
                response_deserializer=cohort__pb2.RegenerateSlotsResponse.FromString,
                _registered_method=True)


class SlotServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAvailableSlots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSlotsForHost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSlot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSlot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSlot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegenerateSlots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SlotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAvailableSlots': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableSlots,
                    request_deserializer=cohort__pb2.GetAvailableSlotsRequest.FromString,
                    response_serializer=cohort__pb2.ListSlotsResponse.SerializeToString,
            ),
            'ListSlotsForHost': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSlotsForHost,
                    request_deserializer=cohort__pb2.ListSlotsForHostRequest.FromString,
                    response_serializer=cohort__pb2.ListSlotsResponse.SerializeToString,
            ),
            'CreateSlot': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSlot,
                    request_deserializer=cohort__pb2.CreateSlotRequest.FromString,
                    response_serializer=cohort__pb2.SlotModel.SerializeToString,
            ),
            'UpdateSlot': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSlot,
                    request_deserializer=cohort__pb2.UpdateSlotRequest.FromString,
                    response_serializer=cohort__pb2.SlotModel.SerializeToString,
            ),
            'DeleteSlot': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSlot,
                    request_deserializer=cohort__pb2.DeleteSlotRequest.FromString,
                    response_serializer=cohort__pb2.StatusResponse.SerializeToString,
            ),
            'RegenerateSlots': grpc.unary_unary_rpc_method_handler(
                    servicer.RegenerateSlots,
                    request_deserializer=cohort__pb2.RegenerateSlotsRequest.FromString,
                    response_serializer=cohort__pb2.RegenerateSlotsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cohort.SlotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cohort.SlotService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SlotService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAvailableSlots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.SlotService/GetAvailableSlots',
            cohort__pb2.GetAvailableSlotsRequest.SerializeToString,
            cohort__pb2.ListSlotsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSlotsForHost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.SlotService/ListSlotsForHost',
            cohort__pb2.ListSlotsForHostRequest.SerializeToString,
            cohort__pb2.ListSlotsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSlot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.SlotService/CreateSlot',
            cohort__pb2.CreateSlotRequest.SerializeToString,
            cohort__pb2.SlotModel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSlot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.SlotService/UpdateSlot',
            cohort__pb2.UpdateSlotRequest.SerializeToString,
            cohort__pb2.SlotModel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSlot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.SlotService/DeleteSlot',
            cohort__pb2.DeleteSlotRequest.SerializeToString,
            cohort__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegenerateSlots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.SlotService/RegenerateSlots',
            cohort__pb2.RegenerateSlotsRequest.SerializeToString,
            cohort__pb2.RegenerateSlotsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BookingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListBookings = channel.unary_unary(
                '/cohort.BookingService/ListBookings',
                request_serializer=cohort__pb2.ListBookingsRequest.SerializeToString,
                response_deserializer=cohort__pb2.ListBookingsResponse.FromString,
                _registered_method=True)
        self.GetBookingById = channel.unary_unary(
                '/cohort.BookingService/GetBookingById',
                request_serializer=cohort__pb2.GetBookingRequest.SerializeToString,
                response_deserializer=cohort__pb2.BookingModel.FromString,
                _registered_method=True)
        self.CreateBooking = channel.unary_unary(
                '/cohort.BookingService/CreateBooking',
                request_serializer=cohort__pb2.CreateBookingRequest.SerializeToString,
                response_deserializer=cohort__pb2.BookingModel.FromString,
                _registered_method=True)
        self.CancelBooking = channel.unary_unary(
                '/cohort.BookingService/CancelBooking',
                request_serializer=cohort__pb2.CancelBookingRequest.SerializeToString,
                response_deserializer=cohort__pb2.BookingModel.FromString,
                _registered_method=True)


class BookingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListBookings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBookingById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBooking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelBooking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListBookings': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBookings,
                    request_deserializer=cohort__pb2.ListBookingsRequest.FromString,
                    response_serializer=cohort__pb2.ListBookingsResponse.SerializeToString,
            ),
            'GetBookingById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookingById,
                    request_deserializer=cohort__pb2.GetBookingRequest.FromString,
                    response_serializer=cohort__pb2.BookingModel.SerializeToString,
            ),
            'CreateBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBooking,
                    request_deserializer=cohort__pb2.CreateBookingRequest.FromString,
                    response_serializer=cohort__pb2.BookingModel.SerializeToString,
            ),
            'CancelBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelBooking,
                    request_deserializer=cohort__pb2.CancelBookingRequest.FromString,
                    response_serializer=cohort__pb2.BookingModel.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cohort.BookingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cohort.BookingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BookingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.BookingService/ListBookings',
            cohort__pb2.ListBookingsRequest.SerializeToString,
            cohort__pb2.ListBookingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBookingById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.BookingService/GetBookingById',
            cohort__pb2.GetBookingRequest.SerializeToString,
            cohort__pb2.BookingModel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.BookingService/CreateBooking',
            cohort__pb2.CreateBookingRequest.SerializeToString,
            cohort__pb2.BookingModel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.BookingService/CancelBooking',
            cohort__pb2.CancelBookingRequest.SerializeToString,
            cohort__pb2.BookingModel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EnrollerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateEnroller = channel.unary_unary(
                '/cohort.EnrollerService/CreateEnroller',
                request_serializer=cohort__pb2.CreateEnrollerRequest.SerializeToString,
                response_deserializer=cohort__pb2.EnrollerModel.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_unary(
                '/cohort.EnrollerService/Subscribe',
                request_serializer=cohort__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=cohort__pb2.SubscriptionModel.FromString,
                _registered_method=True)
        self.Unsubscribe = channel.unary_unary(
                '/cohort.EnrollerService/Unsubscribe',
                request_serializer=cohort__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=cohort__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.CreateSlotRequest = channel.unary_unary(
                '/cohort.EnrollerService/CreateSlotRequest',
                request_serializer=cohort__pb2.SlotRequestCreateRequest.SerializeToString,
                response_deserializer=cohort__pb2.SlotRequestModel.FromString,
                _registered_method=True)
        self.ListSubscriptions = channel.unary_unary(
                '/cohort.EnrollerService/ListSubscriptions',
                request_serializer=cohort__pb2.ListSubscriptionsRequest.SerializeToString,
                response_deserializer=cohort__pb2.ListSubscriptionsResponse.FromString,
                _registered_method=True)
        self.ListSlotRequestsForTeacher = channel.unary_unary(
                '/cohort.EnrollerService/ListSlotRequestsForTeacher',
                request_serializer=cohort__pb2.ListSlotRequestsRequest.SerializeToString,
                response_deserializer=cohort__pb2.ListSlotRequestsResponse.FromString,
                _registered_method=True)


class EnrollerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateEnroller(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unsubscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSlotRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSubscriptions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSlotRequestsForTeacher(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnrollerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateEnroller': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEnroller,
                    request_deserializer=cohort__pb2.CreateEnrollerRequest.FromString,
                    response_serializer=cohort__pb2.EnrollerModel.SerializeToString,
            ),
            'Subscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=cohort__pb2.SubscribeRequest.FromString,
                    response_serializer=cohort__pb2.SubscriptionModel.SerializeToString,
            ),
            'Unsubscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Unsubscribe,
                    request_deserializer=cohort__pb2.SubscribeRequest.FromString,
                    response_serializer=cohort__pb2.StatusResponse.SerializeToString,
            ),
            'CreateSlotRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSlotRequest,
                    request_deserializer=cohort__pb2.SlotRequestCreateRequest.FromString,
                    response_serializer=cohort__pb2.SlotRequestModel.SerializeToString,
            ),
            'ListSubscriptions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSubscriptions,
                    request_deserializer=cohort__pb2.ListSubscriptionsRequest.FromString,
                    response_serializer=cohort__pb2.ListSubscriptionsResponse.SerializeToString,
            ),
            'ListSlotRequestsForTeacher': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSlotRequestsForTeacher,
                    request_deserializer=cohort__pb2.ListSlotRequestsRequest.FromString,
                    response_serializer=cohort__pb2.ListSlotRequestsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cohort.EnrollerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cohort.EnrollerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EnrollerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateEnroller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.EnrollerService/CreateEnroller',
            cohort__pb2.CreateEnrollerRequest.SerializeToString,
            cohort__pb2.EnrollerModel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.EnrollerService/Subscribe',
            cohort__pb2.SubscribeRequest.SerializeToString,
            cohort__pb2.SubscriptionModel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unsubscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.EnrollerService/Unsubscribe',
            cohort__pb2.SubscribeRequest.SerializeToString,
            cohort__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSlotRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.EnrollerService/CreateSlotRequest',
            cohort__pb2.SlotRequestCreateRequest.SerializeToString,
            cohort__pb2.SlotRequestModel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSubscriptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.EnrollerService/ListSubscriptions',
            cohort__pb2.ListSubscriptionsRequest.SerializeToString,
            cohort__pb2.ListSubscriptionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSlotRequestsForTeacher(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohort.EnrollerService/ListSlotRequestsForTeacher',
            cohort__pb2.ListSlotRequestsRequest.SerializeToString,
            cohort__pb2.ListSlotRequestsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
